### PR TITLE
Fixes segfault with XWayland, saves login & settings

### LINKED ISSUE #2: Segmentation fault (core dumped)
Getting the above error when running with no other output. xhost + did not resolve the issue. Any kind of troubleshooting steps I can take?

### PR DESCRIPTION
**Pull request by jfyne**
I applied some docker best practices and figured out the segfault that people are reporting... I think

The problem for me was Xwayland and the root user. So I added a regular user to the image which then allows Parsec to start without the segfault. This might fix #2 

Can you try it out and see if it works for you?

### CODE REVIEW

**Comment by jfyne** [comment]
Added a docker `mount` to the home directory which now allows settings and login to be saved across runs. Might fix #1

**Comment by kajmaj87** [comment]
@jfyne Thanks for your contribution! I've checked it locally, client seems to be working fine and settings are persisted, but didn't start any game server as I do not have any right now.

Don't you think that mentioning which libs do what in comments is good for later in case someone want's to add support for other videocards or similar? I've noticed you deleted them.

**Comment by jfyne** [comment]
Sure that's probably a good idea!

I've actually been messing around with my own version of this but without all the Intel stuff. For me in this version the sound didn't work and I have managed to fix it. https://github.com/jfyne/docker-parsec

If you want I can try and port across the extra stuff I did to your repo too

**Comment by kajmaj87** [comment]
What did you do extra?

**Comment by kajmaj87** [comment]
@jfyne Hmm I just looked at your version and understand what you mean by "extra" :smile: 
What I don't understand is how is it possible that your dependencies are so small? Just those few lines in Dockerfile is enough?

**Comment by jfyne** [comment]
Well, when you run `dpkg -i parsec-linux.deb` it indicates to `apt` what dependencies are required and missing. If you then follow that up with the `apt-get -f install` it goes ahead and installs the missing dependencies along with parsec.

The other thing I added was pulseaudio and some settings for it

**Comment by kajmaj87** [comment]
Ok, I feel stupid now. Such a simple and elegant solution! Did not think about it. When I someday get back to using parsec I'll have to adapt this to your solution.

**Pull request merged**
